# -*- coding: utf-8 -*-
"""Bharath_B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NH9wiRYIXxBzKKmMYi1puYIpwNqV05i5
"""

import csv
dict = {}
with open('/sample_input.txt', 'r') as fd:
    reader = csv.reader(fd)
    i=0
    for row in reader:
      if(len(row)>0):
        i+=1
        if(i==1):
          num=int(row[0].split(':')[1])
        if(i>2):
          dict[row[0].split(':')[0]] = int(row[0].split(':')[1])
        print(row[0].split(':'))



sorted_values = sorted(dict.values()) # Sort the values
sorted_dict = {}

for i in sorted_values:
    for k in dict.keys():
        if dict[k] == i:
            sorted_dict[k] = dict[k]
            break

print(sorted_dict)

#numEmployees=3
#print(sorted_dict)

import numpy as np
#n=3 

data = list(sorted_dict.values())
value_array = np.array(data)
small_array = []
big_array = []
print(value_array)

#value_array=[999,2799,7980,22349,229900]
print(len(value_array))
#n=3
big_array=[]
i=0
j=0
for i in range(len(value_array)-num):
  small_array=[]
  for j in range(i,i+num):
    small_array.append(value_array[j])
  big_array.append(small_array)
print(big_array)

for i in big_array:
  diff=i[num-1]-i[0]
  difference=[]
  difference.append(diff)
index=difference.index(min(difference))  
print(big_array[index])


def get_key(val):
    for key, value in sorted_dict.items():
         if val == value:
             return key    

j=0
output=[]
for i in range(num):
  output.append(get_key(big_array[index][j]))
  j=j+1

print(output)
d=big_array[index][num-1]-big_array[index][0] #Calculating difference between Highest and Lowest Price
print(d)

file1 = open('sample_output.txt', 'w') 
s="The goodies selected for distribution are: \n"

file1.write(s)

for i in range(num):
  s= get_key(big_array[index][i])
  file1.write(str(s))
  file1.write(" ")
  f= big_array[index][i]
  file1.write(str(f))
  file1.write("\n")
   
  
  

s="\n"
file1.write(str(s)) 

s="And the difference between the chosen goodie with highest price and the lowest price is "+str(d)
file1.write(str(s)) 


file1.close()

